// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Xz41gWf2vW42mVSEoKtfJkdIa2Fogcg',
    appId: '1:639009775699:web:74e688e2b1b3b3bc78a6a6',
    messagingSenderId: '639009775699',
    projectId: 'sw2627-s131-1-flutter-edulens',
    authDomain: 'sw2627-s131-1-flutter-edulens.firebaseapp.com',
    storageBucket: 'sw2627-s131-1-flutter-edulens.firebasestorage.app',
    measurementId: 'G-QCSJW9063S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmziHWXj5sctyXChETqdSKKeOR2FPW2D8',
    appId: '1:639009775699:android:8dd40afd6aa3cbfc78a6a6',
    messagingSenderId: '639009775699',
    projectId: 'sw2627-s131-1-flutter-edulens',
    storageBucket: 'sw2627-s131-1-flutter-edulens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgsd1Hqj6ECbe46DvppqNYiyKdfqrclSk',
    appId: '1:639009775699:ios:8efabb5084b5ad4378a6a6',
    messagingSenderId: '639009775699',
    projectId: 'sw2627-s131-1-flutter-edulens',
    storageBucket: 'sw2627-s131-1-flutter-edulens.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgsd1Hqj6ECbe46DvppqNYiyKdfqrclSk',
    appId: '1:639009775699:ios:8c6eff7c43479aa278a6a6',
    messagingSenderId: '639009775699',
    projectId: 'sw2627-s131-1-flutter-edulens',
    storageBucket: 'sw2627-s131-1-flutter-edulens.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterEduLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Xz41gWf2vW42mVSEoKtfJkdIa2Fogcg',
    appId: '1:639009775699:web:d73bebf32ae709a378a6a6',
    messagingSenderId: '639009775699',
    projectId: 'sw2627-s131-1-flutter-edulens',
    authDomain: 'sw2627-s131-1-flutter-edulens.firebaseapp.com',
    storageBucket: 'sw2627-s131-1-flutter-edulens.firebasestorage.app',
    measurementId: 'G-DQS2Q5CSBE',
  );
}
